# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerComponents/Ex4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1067, 566)
        self.mLabel1 = QtWidgets.QLabel(Form)
        self.mLabel1.setGeometry(QtCore.QRect(70, 80, 300, 300))
        self.mLabel1.setStyleSheet("background-color: rgb(46, 204, 113);")
        self.mLabel1.setText("")
        self.mLabel1.setObjectName("mLabel1")
        self.mLabel2 = QtWidgets.QLabel(Form)
        self.mLabel2.setGeometry(QtCore.QRect(380, 80, 300, 300))
        self.mLabel2.setStyleSheet("background-color: rgb(46, 204, 113);")
        self.mLabel2.setText("")
        self.mLabel2.setObjectName("mLabel2")
        self.mLabel3 = QtWidgets.QLabel(Form)
        self.mLabel3.setGeometry(QtCore.QRect(690, 80, 300, 300))
        self.mLabel3.setStyleSheet("background-color: rgb(46, 204, 113);")
        self.mLabel3.setText("")
        self.mLabel3.setObjectName("mLabel3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(470, 430, 89, 25))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.Spin) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Spin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
