# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerComponents/ComposantTP4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1369, 921)
        self.mLabel = QtWidgets.QLabel(Form)
        self.mLabel.setGeometry(QtCore.QRect(120, 120, 640, 480))
        self.mLabel.setAutoFillBackground(False)
        self.mLabel.setStyleSheet("background-color: rgb(46, 204, 113);")
        self.mLabel.setText("")
        self.mLabel.setObjectName("mLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 610, 641, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mLineEdit.setEnabled(True)
        self.mLineEdit.setAutoFillBackground(False)
        self.mLineEdit.setReadOnly(True)
        self.mLineEdit.setObjectName("mLineEdit")
        self.horizontalLayout_2.addWidget(self.mLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_2.addItem(spacerItem)
        self.mButtonBrowse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.mButtonBrowse.setEnabled(True)
        self.mButtonBrowse.setAutoFillBackground(False)
        self.mButtonBrowse.setObjectName("mButtonBrowse")
        self.horizontalLayout_2.addWidget(self.mButtonBrowse)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(790, 340, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mButtonN = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mButtonN.setObjectName("mButtonN")
        self.verticalLayout.addWidget(self.mButtonN)
        self.mButtonP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mButtonP.setObjectName("mButtonP")
        self.verticalLayout.addWidget(self.mButtonP)

        self.retranslateUi(Form)
        self.mButtonBrowse.clicked.connect(Form.LoadFiles) # type: ignore
        self.mButtonN.clicked.connect(Form.Next) # type: ignore
        self.mButtonP.clicked.connect(Form.Previous) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mLineEdit.setText(_translate("Form", "Chemin vers l\'image chargée"))
        self.mButtonBrowse.setText(_translate("Form", "..."))
        self.mButtonN.setText(_translate("Form", "Next"))
        self.mButtonP.setText(_translate("Form", "Previous"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
